### ISSUE TITLE
Compare with arcade 2.4

### ISSUE THREAD

**Issue by einarf** [GeorgeShao/arcadeplus#2]
Hello

I noticed this fun fork a while ago and wanted to run the perf test when arcade 2.4 was released. It's now out with some significant optimizations. Running the perf tests with 200 lines was not really enough to make a fair comparison so I tried with 2_000 and 20_000.

Here are the results:

![compare2000](https://user-images.githubusercontent.com/5418180/89140196-35c64c00-d541-11ea-9712-1c92f9df9f80.PNG)

![compare20000](https://user-images.githubusercontent.com/5418180/89140210-3eb71d80-d541-11ea-81ed-685c1fce6486.PNG)

I did not look into why arcadeplus for some reason starts at 120 fps so the early part of the curve is not that easy to make sense of. I also noticed that processing time is not included in the perf test. arcadeplus do have higher processing time, but I guess it doesn't matter for < 2000 lines.

You could probably benefit greatly from rebasing with the current 2.4 branch (maintenance). It's not a trivial amount of work, but you could definitely see more speed improvements. There are valid use cases for caching primitives at least as long as they don't move around too much and the amount of primitives are not enormous. The arcadeplus perf test peaks at 600MB memory at the end of the 20k version while arcade peaks at around 85MB.

Release notes : https://arcade.academy/release_notes.html?highlight=release#version-2-4

Have a nice day.

**Comment by einarf** [comment]
Forgot to post the perf test with vsync. They are a bit more reasonable as a comparison.

![compare2k](https://user-images.githubusercontent.com/5418180/89212817-72875700-d5c4-11ea-8d18-3d998321ac38.PNG)

![compare20k](https://user-images.githubusercontent.com/5418180/89212824-74511a80-d5c4-11ea-9861-04358fd92b2d.PNG)

**Comment by GeorgeShao** [comment]
Thanks! I'm quite busy with an internship and other coding-related projects right now, but i'll rebase soon when I have the time. I'd just like to mention that usually I run the line drawing stress test on a relatively low-end laptop:

- i7-8550U, 4c 8t
- DDR4 16GB @ 2666
- Integrated graphics (Intel UHD 620)

...and I do that because the vast majority of the people I know that use Arcade are high school students (usually taking a comp sci course) who usually code on laptops with similar (or worse) specs.

**Comment by einarf** [comment]
> Thanks! I'm quite busy with an internship and other coding-related projects right now, but i'll rebase soon when I have the time. I'd just like to mention that usually I run the line drawing stress test on a relatively low-end laptop:

Cool. I'll run perf tests on similar hardware and report back. 

> ...and I do that because the vast majority of the people I know that use Arcade are high school students (usually taking a comp sci course) who usually code on laptops with similar (or worse) specs.

The arcadeplus project definitely provides a performant alternative to arcade 2.3.* especially for shape drawing and will continue to be a good alternative for people who rely on arcade 2.3. It's great that you took your time to provide this option.

**Comment by einarf** [comment]
perf test on a 2013 macbook. arcade 2.4 vs arcadeplus. This was actually the worst platform on arcade 2.3.

* 2.7 GHz Quad-Core Intel Core i7
* 16 GB 1600 MHz DDR3
* Intel HD Graphics 4000 1536 MB (It has a 650M as well, but this one is broken)


<img width="537" alt="Screenshot 2020-08-03 at 21 49 03" src="https://user-images.githubusercontent.com/5418180/89221508-ae75e880-d5d3-11ea-9c2b-782b3654f58a.png">

<img width="551" alt="Screenshot 2020-08-03 at 21 49 22" src="https://user-images.githubusercontent.com/5418180/89221560-c6e60300-d5d3-11ea-9613-b97ba91ca1e0.png">

**Comment by GeorgeShao** [comment]
That's weird. I always yielded far higher frame rates by using arcadeplus instead of arcade 2.3.x.

**Comment by einarf** [comment]
> That's weird. I always yielded far higher frame rates by using arcadeplus instead of arcade 2.3.x.

Definitely, but I am comparing to arcade 2.4. The version you get now by default with `pip`

**Comment by GeorgeShao** [comment]
ohhh, i misread your message. nevermind

**Comment by GeorgeShao** [comment]
I've been spending the afternoon attempting to do this and the performance between arcadeplus vs arcade 2.4 is negligible. I've run multiple tests, and each time, there is little-to-no difference on my machine. It seems that it varies significantly depending on RAM speed, gpu...etc.

![image](https://user-images.githubusercontent.com/31512688/89228381-7fe51700-d5ad-11ea-9579-7ea279f4fedc.png)

I don't think it's really worth my time to figure out how to implement the new changes. If you'd like to, you are welcome to make a PR to this repo, but personally I won't be pursuing this issue.

Thank you!

**Comment by einarf** [comment]
More than fair. It's a lot of work to rebase almost 1000 commits. I saw you updated readme as well 👍 

Have fun with your internship and other coding-related projects!
